"""Pydantic schemas for API requests and responses."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class SubmissionSummary(BaseModel):
    id: str = Field(description="Unique submission id generated by the backend.")
    student_id: str = Field(description="Student identifier sent with the upload.")
    student_name: str = Field(description="Student name sent with the upload.")
    claimed_category: str = Field(description="Claimed MAR category.")
    claimed_points: int = Field(description="Claimed MAR points.")
    decision: str | None = Field(description="Final workflow decision: admin_review or likely_valid.")
    review_status: str | None = Field(description="Human review status derived from the decision.")
    risk_score: float | None = Field(description="Computed fraud risk score.")
    decision_confidence: float | None = Field(description="Confidence reported by the final decision step.")
    processing_status: str = Field(description="Current processing state of the submission.")
    file_name: str = Field(description="Original uploaded file name.")
    created_at: str = Field(description="Submission creation timestamp in UTC.")
    updated_at: str = Field(description="Latest update timestamp in UTC.")


class SubmissionDetail(SubmissionSummary):
    explanation: str | None = Field(description="Final human-readable workflow explanation.")
    state: dict[str, Any] = Field(description="Complete stored workflow state.")
    timeline: list[dict[str, Any]] = Field(description="Step-by-step workflow timeline.")
    alerts: list[dict[str, Any]] = Field(description="Fraud-related alerts generated from the final state.")


class DashboardSummary(BaseModel):
    total_submissions: int = Field(description="Number of stored processed submissions.")
    average_risk_score: float = Field(description="Average fraud risk score across stored submissions.")
    rule_validation_rate: float = Field(description="Percentage of submissions that passed rule validation.")
    duplicate_rejections: int = Field(description="Number of submissions flagged as duplicates.")
    admin_review_required: int = Field(description="Count of submissions routed to admin review.")
    likely_valid_pending_human_confirmation: int = Field(description="Count of submissions routed as likely valid.")

class ToolCatalogItem(BaseModel):
    name: str = Field(description="Tool name visible to the planner.")
    description: str = Field(description="Short explanation of what the tool does.")
